"""
Outbound email behind a provider interface (mirrors the messaging-provider
pattern). GmailProvider sends via the Gmail API once OAuth is authorized;
otherwise a StubProvider records the message to MessageLog so order-email logic
is testable now. Callers never change when the real sender is active.
"""
from __future__ import annotations

import base64
from email.mime.text import MIMEText
from typing import Protocol

from .models import MessageLog


class EmailProvider(Protocol):
    name: str
    def send(self, session, to: str, subject: str, html: str, kind: str = "",
             cc: str = "") -> dict: ...


class StubEmailProvider:
    name = "stub"
    def send(self, session, to, subject, html, kind="", cc=""):
        log = MessageLog(provider="email-stub",
                         to_number=to + (f" cc:{cc}" if cc else ""),
                         body=f"{subject}\n\n{html}",
                         kind=kind or "email", status="logged")
        session.add(log); session.commit()
        return {"sent": False, "provider": self.name, "logged_id": log.id}


class GmailProvider:
    name = "gmail"
    def __init__(self, creds):
        self._creds = creds
    def send(self, session, to, subject, html, kind="", cc=""):
        from googleapiclient.discovery import build
        svc = build("gmail", "v1", credentials=self._creds, cache_discovery=False)
        msg = MIMEText(html, "html")
        msg["to"] = to; msg["subject"] = subject
        if cc:
            msg["cc"] = cc
        raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
        res = svc.users().messages().send(userId="me", body={"raw": raw}).execute()
        session.add(MessageLog(provider="gmail",
                               to_number=to + (f" cc:{cc}" if cc else ""),
                               kind=kind or "email", body=subject, status="sent"))
        session.commit()
        return {"sent": True, "provider": self.name, "message_id": res.get("id")}


def get_provider() -> EmailProvider:
    from . import google_oauth
    creds = google_oauth.load_creds()
    return GmailProvider(creds) if creds else StubEmailProvider()


# --------------------------------------------------------------- composition
def compose_order_email(order_name: str, rows: list) -> tuple[str, str]:
    """Order-placement email: subject + HTML table of the finalised order."""
    subject = f"Isha Life — Purchase Order {order_name}"
    head = ("US SKU", "Product", "Global SKU", "Vendor", "Sea", "Air", "Case", "HSN")
    def cell(v): return f"<td style='padding:4px 8px;border-bottom:1px solid #eee'>{'' if v is None else v}</td>"
    trs = "".join(
        "<tr>" + "".join(cell(r.get(k)) for k in
        ("us_sku", "name", "global_sku", "vendor", "final_sea_qty", "final_air_qty",
         "case_size", "hsn_code")) + "</tr>" for r in rows)
    ths = "".join(f"<th style='text-align:left;padding:4px 8px;border-bottom:2px solid #333'>{h}</th>" for h in head)
    html = (f"<p>Please find the purchase order <b>{order_name}</b> below "
            f"({len(rows)} line items).</p>"
            f"<table style='border-collapse:collapse;font-family:Arial;font-size:13px'>"
            f"<tr>{ths}</tr>{trs}</table>"
            f"<p style='color:#888;font-size:12px'>Generated by Isha Life Ordering Tool.</p>")
    return subject, html


def compose_vendor_email(order_name: str, vendor_name: str, rows: list) -> tuple[str, str]:
    """Per-vendor PO: just item name + quantity for that vendor's lines."""
    subject = f"Purchase Order {order_name} — {vendor_name}"
    def cell(v): return f"<td style='padding:4px 10px;border-bottom:1px solid #eee'>{'' if v is None else v}</td>"
    trs = "".join("<tr>" + cell(r.get("name")) + cell(r.get("qty")) + "</tr>" for r in rows)
    total = sum(int(r.get("qty") or 0) for r in rows)
    html = (f"<p>Hello {vendor_name},</p><p>Please supply the following for order "
            f"<b>{order_name}</b>:</p>"
            f"<table style='border-collapse:collapse;font-family:Arial;font-size:13px'>"
            f"<tr><th style='text-align:left;padding:4px 10px;border-bottom:2px solid #333'>Item</th>"
            f"<th style='text-align:left;padding:4px 10px;border-bottom:2px solid #333'>Qty</th></tr>"
            f"{trs}</table><p>Total units: {total}.</p>"
            f"<p>Thank you.</p>")
    return subject, html


def compose_new_user_email(email: str, name: str, manage_url: str = "") -> tuple[str, str]:
    """Notify coordinators that a new user signed in and needs list access."""
    subject = f"Isha Ordering — new user awaiting access: {email}"
    who = f"{name} ({email})" if name else email
    link = (f"<p><a href='{manage_url}'>Open Users &amp; Access</a> to grant lists.</p>"
            if manage_url else "<p>Open <b>Users &amp; Access</b> to grant lists.</p>")
    html = (f"<p><b>{who}</b> just signed in to the Isha Life Ordering tool and "
            f"currently has no list access.</p>"
            f"<p>They'll see a waiting screen until a coordinator assigns at least "
            f"one reorder list.</p>{link}"
            f"<p style='color:#888;font-size:12px'>Sent automatically by the Ordering tool.</p>")
    return subject, html


def compose_change_summary(order_name: str, events: list) -> tuple[str, str]:
    """Change-summary email from the order's lifecycle events."""
    subject = f"Isha Life — Changes to Order {order_name}"
    items = "".join(
        f"<li><b>{e['type'].replace('_',' ')}</b> "
        f"{('('+e['sku']+') ') if e.get('sku') else ''}{e.get('note','')} "
        f"<span style='color:#888'>— {(e.get('at') or '')[:16].replace('T',' ')}</span></li>"
        for e in events)
    html = (f"<p>The following changes were recorded on order <b>{order_name}</b>:</p>"
            f"<ul>{items or '<li>No changes.</li>'}</ul>")
    return subject, html
